### ISSUE TITLE
Ignore suspended cards and count cards In Learning when calculating Burden

### ISSUE THREAD

**Issue by aleksejrs** [Luc-Mcgrady/Anki-Search-Stats-Extended#1]
Suspended cards should not be counted in burden by default (a checkbox?).
Cards in learning should.

Also, Burden is being renamed to Load in FSRS4Anki Helper: https://github.com/open-spaced-repetition/fsrs4anki-helper/pull/373

**Comment by Luc-Mcgrady** [comment]
> Suspended cards should not be counted in burden by default (a checkbox?)

The original reason I didn't remove suspended cards is that even though it didn't really make sense to include them it still gave people a choice to add `-is:suspended` to their search and toggle it themselves.

The button is a great idea, I'll add it when I get around to it.

> Cards in learning should.

The way its set up the graphs actually use the data from the default Anki "Review Intervals" graph meaning I couldn't make any adjustments that involve more than modifying the search content (like including learning cards) without rewriting the interval code from scratch.

Also what would be the lower threshold for learning cards to be included? 1 day? for reference a learning card with a 10 minute interval would alone have a burden of 144 which would pretty much render the statistic obsolete while learning cards are there. I think the way Anki does it where the interval is the same interval that the card will attain when it graduates.

> Also, Burden is being renamed to Load in FSRS4Anki Helper

I'll rename Burden to Burden/Load to avoid confusion with people familiar with the FSRS helper's stat.

"Daily load distribution" vs "Burden/Load distribution" vs "Load distribution"? I think the explanation at the bottom would clear up any ambiguity regardless.

**Comment by aleksejrs** [comment]
> The way its set up the graphs actually use the data from the default Anki "Review Intervals" graph meaning I couldn't make any adjustments that involve more than modifying the search (like including learning cards) without rewriting the interval code from scratch.

I wanted it to be helpful for https://github.com/lune-stone/anki-addon-limit-new-by-young, but I guess learning cards are not that important for configuring that add-on, and it ignores overdue cards and has its own limit utilization report, too.

> Also what would be the lower threshold for learning cards to be included? 1 day? for reference a learning card with a 10 minute interval would alone have a burden of 144 which would pretty much render the statistic obsolete while learning cards are there.

Since burden is measured in reviews, it should probably be the number of steps remaining, or just 1 per card.

Of course, there are Difficulty/Ease and answer time and target retention (not that they would change much for learning cards)… The above add-on is the only add-on like that currently working though.

> I think the way Anki does it where the interval is the same interval that the card will attain when it graduates.

Huh, it seems like all three add-ons ignore cards due today. Then there is no real point in counting learning cards.

> "Daily load distribution" vs "Burden/Load distribution" vs "Load distribution"? I think the explanation at the bottom would clear up any ambiguity regardless.

I think the word "distribution" makes "load" a poor description. What would then be the reason for dividing the farther numbers? 🤔

**Comment by Luc-Mcgrady** [comment]
Is it ok if I just change the title then or is there some other feature you want me to add regarding that addon to make it more useful? I'll probably avoid changing the distribution graphs if I can. I'm not very familiar with that addon so can't tell at a glance how adding the learning cards to the graph would help.

**Comment by aleksejrs** [comment]
I don't care about the learning cards, since it only considers the future and you are supposed to learn the learning cards today.
Only that the suspended cards should be ignored.
