### ISSUE TITLE
Work around aqt.mediasrv._check_dynamic_request_permissions instead of outright removing it

### ISSUE THREAD

**Issue by iamllama** [Luc-Mcgrady/Anki-Search-Stats-Extended#11]
I don't know how serious the threat of malicious js on templates is, but removing the function that limits api access seems a bit overkill.

Anki seems to be complaining about the 3 extra post handlers added by the addon, namely `cardSearch`, `cardData`, and `revlogs`

So far i've come up with two options that seem to work:

1. Change the Content-Type in `endpoint` to `application/binary`

This gets it past the check in `_check_dynamic_request_permissions`, which is the only thing stopping it

```diff
diff --git a/src/ts/search.ts b/src/ts/search.ts
index e5e8e67..6e16b8d 100644
--- a/src/ts/search.ts
+++ b/src/ts/search.ts
@@ -1,7 +1,11 @@
 import { realFetch } from "./root"
 
 async function endpoint(endpoint: string, body?: string) {
-    const resp = await realFetch(`/_anki/${endpoint}`, { method: "POST", body })
+    const resp = await realFetch(`/_anki/${endpoint}`, {
+        method: "POST",
+        body,
+        headers: { "Content-Type": "application/binary" },
+    })
     const blob = await resp.text()
     return JSON.parse(blob)
 }

```

2) Or, monkeypatch `_check_dynamic_request_permissions` to account for those handlers:

```diff
diff --git a/__init__.py b/__init__.py
index 9e1f49d..39d102f 100644
--- a/__init__.py
+++ b/__init__.py
@@ -35,8 +35,21 @@ from aqt.mediasrv import post_handlers
 import aqt.mediasrv
 
 
-# Im not smart enough to understand why this function exists but I do know it existing breaks my addon.
-aqt.mediasrv._check_dynamic_request_permissions = lambda: None 
+def new_check_dynamic_request_permissions(_old):
+    from urllib.parse import urlparse
+    referer = urlparse(request.headers.get("Referer", ""))
+    # explicitly approve the 3 extra api endpoints used by the addon
+    if referer.path == "/graphs" and request.path in (
+        "/_anki/cardSearch",
+        "/_anki/cardData",
+        "/_anki/revlogs",
+    ):
+        return
+    return _old()
+
+
+aqt.mediasrv._check_dynamic_request_permissions = wrap(aqt.mediasrv._check_dynamic_request_permissions, new_check_dynamic_request_permissions, "around")
 
 def card_search() -> bytes:
     search = request.data

```

Understandably, one might think why even bother 🤔. But doing this in the python side means the user has already chosen to trust the search stats addon. The same can't be said for any random js that tags along in an imported shared deck, perhaps

Thanks for your time!

**Comment by iamllama** [comment]
A search brought up https://skerritt.blog/anki-0day/. The 3 CVEs in there have already been reported, but there are attack vectors that were thought to be unfeasible **on the assumption** that `_extract_page_context` works as intended.

`_check_dynamic_request_permissions` is the one that calls that function and performs those checks. The danger in removing it isn't unfounded and theoretical anymore, and I honestly think this issue should be fixed as soon as possible

**Comment by Luc-Mcgrady** [comment]
Solution 1 seems best. 
If you could PR it that would be great but I could commit it myself if you want.

No need to thank *me* for *my* time when you're the one who came up with 2 solutions to the same problem :smile:.
