### ISSUE TITLE
The new warnings are a tad conspicuous

### ISSUE THREAD

**Issue by iamllama** [Luc-Mcgrady/Anki-Search-Stats-Extended#16]
The new "may be inaccurate when all history is not selected" warning is appreciated, albeit a tad too bright.

It'd be nice to have them greyed out instead of displayed in a bright yellow.
It'd also be nice to have it hidden when the "all history" option is actually selected 😅 

Anki seems to set the `days` param of the `graphs` endpoint to 0 when all history is selected

https://github.com/ankitects/anki/blob/87ccd24efd0ea635558b1679614b6763e4f514eb/ts/routes/graphs/RangeBox.svelte#L54

which can be obtained via `search_request.days`
https://github.com/Luc-Mcgrady/Anki-Search-Stats-Extended/blob/d37b72ee47cbbcf564e013d8a768c323e3cda618/src/ts/root.ts#L72

~~You could then add and write to a store to propagate this to warning labels perhaps 🤔~~
Seems the existing `searchLimit` store could be used instead

Thanks!

EDIT: Odd, I just noticed you've already dealt with this via `truncated`, but it's still showing up for some reason

**Comment by Luc-Mcgrady** [comment]
I'll probably try to add a hint that theres a "warnings" config attribute somewhere, Theres just no good space for it.
