### ISSUE TITLE
When the graphs disappear and the "Prepare Graphs" button reappears, the window height stays with scrolling and confusing blank space

### ISSUE THREAD

**Issue by aleksejrs** [Luc-Mcgrady/Anki-Search-Stats-Extended#5]
If I change the search query.

**Comment by Luc-Mcgrady** [comment]
![image](https://github.com/user-attachments/assets/2e7b98d4-6976-42ca-925c-b5590e2719a3)

Its the tooltip! Hover over another bar and the extra space will go away.
Thanks! I'll try fix it asap.
