### ISSUE TITLE
Some graphs are too tall

### ISSUE THREAD

**Issue by aleksejrs** [Luc-Mcgrady/Anki-Search-Stats-Extended#6]
When zoomed in to take the full width, many graphs barely fit even without their descriptions and settings.
![Screenshot_2024-07-16_18-58-38](https://github.com/user-attachments/assets/00266866-32a8-41ab-b0a7-6c40b58bf4c0)

**Comment by aleksejrs** [comment]
Does it have to use only half the width to have half the height?

**Comment by Luc-Mcgrady** [comment]
All Anki's bar charts are rendered at 600x250 or 0.416 
![image](https://github.com/user-attachments/assets/33312c20-c7bf-48eb-be51-cc380d0ae09d)

I'll add width and height settings to the config so you can find whatever ratio suits you.
